cmake_minimum_required(VERSION 3.8) 
set(CMAKE_CXX_STANDARD 23) 
project(Components) 
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY E:/K-Engine/bin) 
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY E:/K-Engine/bin) 
add_subdirectory("E:/K-Engine" "E:/K-Engine/bin") 
file(GLOB ComponentSrcs CONFIGURE_DEPENDS "components/*.cpp") 
add_library(${PROJECT_NAME} SHARED ${ComponentSrcs}) 
target_compile_definitions(${PROJECT_NAME} PRIVATE KC_BUILD_DLL) 
target_link_libraries(${PROJECT_NAME} K-Engine) 
set_target_properties(${PROJECT_NAME} PROPERTIES VS_DEBUGGER_WORKING_DIRECTORY "$(ProjectDir) / $(Configuration)")